[platformio]
default_envs = nanoatmega328

[env]
platform = atmelavr@5.1.0
framework = arduino
monitor_speed = 115200
platform_packages =
  platformio/framework-arduino-avr@5.2.0
  platformio/toolchain-atmelavr@1.70300.191015

[env:nanoatmega328]
board = nanoatmega328

[env:nanoatmega328new]
board = nanoatmega328new
